name: Run pytests in conda environment

on: [push]

jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          activate-environment: nwc
          channels: conda-forge
          channel-priority: strict
          environment-file: etc/environment.yml
          python-version: 3.10
          auto-activate-base: false
      - name: Run conda commands
        shell: bash -el {0}
        run: |
          conda info
          conda list
