name: Test pysteps setup

on:
  push:
    branches:
      - testing
  # pull_request:
  #   branches:
  #     - main

jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
      max-parallel: 6

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: my-env
          use-mamba: true

      - name: Update environment
        run: mamba env update -n my-env -f environment-dev.yml

      - name: Check python
        run: python --version

      - name: Check pysteps imports
        run: |
          python -c "import pysteps; print(pysteps.__file__)"
          python -c "from pysteps import motion"
          python -c "from pysteps.motion import vet"
          python -c "from pysteps.motion import proesmans"

      - name: Download pysteps data
        env:
          PYSTEPS_DATA_PATH: ${{github.workspace}}/pysteps_data
        run: python etc/fetch_pysteps_data.py

      - name: Run tests
        env:
          PYSTEPSRC: ${{github.workspace}}/pysteps_data/pystepsrc
        run: pytest
