name: Python Package using Conda

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: nwc
        channels: conda-forge
        channel-priority: strict
        environment-file: environment.yml
        python-version: 3.10
        auto-activate-base: false
    - run: |
        conda info
        conda list
